# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Sakirabiá spellchecker"
skf = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Sakirabiá, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
skf = "TRANSLATE: A spellchecker for Sakirabiá, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.skf"

[windows]
system_product_code = "{09750947-FD94-4D10-B36C-6E4DA40EC103}_is1"
legacy_product_codes = [
    { value = "70614A0D-973A-4119-B4E9-70D40CC342A7", kind = "nsis" },
    { value = "E3BD8A83-5A60-4376-A3CB-122AB59C622A", kind = "nsis" }
]

[package.speller]
name = "Sakirabiá"
version = "0.1.1"

[package.grammar]
name = "Sakirabiá"
version = "0.1.0"

[package.tts-text-proc]
name = "Sakirabiá"
version = "0.1.0"

[package.hyphenator]
name = "Sakirabiá"
version = "0.1.0"
