template = "https://github.com/giellalt/template-lang-und"
rev_id = 278
template_sha = "58c9d1b66bc21da4ce588378206dd02d219954ae"

[replacements]
__GLOTTOLOG_ID__ = "saki1248"
__REPO__ = "lang-skf"
__UND2C__ = "skf"
__UNDEFINED__ = "Sakirabi√°"
__UND__ = "skf"
