template = "https://github.com/giellalt/template-lang-und"
rev_id = 266
template_sha = "0bf1857d37e3d9d859c2f97c9772ed27d291955c"

[replacements]
__GLOTTOLOG_ID__ = "saki1248"
__REPO__ = "lang-skf"
__UND2C__ = "skf"
__UNDEFINED__ = "Sakirabi√°"
__UND__ = "skf"
