template = "https://github.com/giellalt/template-lang-und"
rev_id = 281
template_sha = "818353eecbfc8e1309992f6739dfde72a0afbec0"

[replacements]
__GLOTTOLOG_ID__ = "saki1248"
__REPO__ = "lang-skf"
__UND2C__ = "skf"
__UNDEFINED__ = "Sakirabi√°"
__UND__ = "skf"
