template = "https://github.com/giellalt/template-lang-und"
rev_id = 171
template_sha = "78deab0f9e7009a3e3fdb46beb2e97c5ac41e8e7"

[replacements]
__REPO__ = "lang-skf"
__UND2C__ = "skf"
__UNDEFINED__ = "Sakirabi√°"
__UND__ = "skf"
